// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsvNiFz8kFA28z9ZaGD2SR86jXVCO-Ic8',
    appId: '1:719076173628:web:bb0a036601fec8b6da2039',
    messagingSenderId: '719076173628',
    projectId: 'saro-5e271',
    authDomain: 'saro-5e271.firebaseapp.com',
    storageBucket: 'saro-5e271.firebasestorage.app',
    measurementId: 'G-HY8G2YTL3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVR8nA00fTzlrEcJoW6nOHk0tLDg1OspI',
    appId: '1:719076173628:android:3b3dc3f8058bb154da2039',
    messagingSenderId: '719076173628',
    projectId: 'saro-5e271',
    storageBucket: 'saro-5e271.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_O4BYo11Em7Jti98VS8RxkeSC-T30ljY',
    appId: '1:719076173628:ios:d60388aa29ab2373da2039',
    messagingSenderId: '719076173628',
    projectId: 'saro-5e271',
    storageBucket: 'saro-5e271.firebasestorage.app',
    iosBundleId: 'com.example.saroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_O4BYo11Em7Jti98VS8RxkeSC-T30ljY',
    appId: '1:719076173628:ios:d60388aa29ab2373da2039',
    messagingSenderId: '719076173628',
    projectId: 'saro-5e271',
    storageBucket: 'saro-5e271.firebasestorage.app',
    iosBundleId: 'com.example.saroApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsvNiFz8kFA28z9ZaGD2SR86jXVCO-Ic8',
    appId: '1:719076173628:web:2822cc2d5739ba4ada2039',
    messagingSenderId: '719076173628',
    projectId: 'saro-5e271',
    authDomain: 'saro-5e271.firebaseapp.com',
    storageBucket: 'saro-5e271.firebasestorage.app',
    measurementId: 'G-109YY8D5DN',
  );
}
